### ISSUE TITLE
Efl_Config.h missing path

### ISSUE THREAD

**Issue by hordiales** [OpenMusicKontrollers/oscmux#1]
Doing 'cmake CMakeLists.txt', apt-get install libeina-dev package and make, I got the message Efl_Config.h missing.

I don't know how is the standard/correct way but i fixed adding the path to CMakeLists.txt
	include_directories (/usr/include/efl-1)

OS: Ubuntu 17.04

**Comment by hordiales** [comment]
using 

            include_directories (${PC_EINA_INCLUDE_DIRS})

instead of

            include_directories (${EINA_INCLUDE_DIR})

does the job

**Comment by ventosus** [comment]
Thanks for reporting.

Various EFL libraries have been cumulated in the past and may need different logic to be discovered via CMake, depending on distribution.
